### ISSUE TITLE
Many elements jump in Firefox on Linux.

### ISSUE THREAD

**Issue by opalapo** [bluesky-social/social-app#1593]
**Describe the bug**

~~homeScreenFeedTabs raises and lowers rapidly~~ Most visible elements jump around as mouse scroll event triggers the issue.

Firefox shows multiple errors both ~~flickering~~ jumping and non jumping ~~flickering~~ with:
Error in parsing value for ‘aspect-ratio’.  Declaration dropped. 3 bsky.app:1:1

**To Reproduce**

1. scroll up and down on feed, issue is intermittent

sometimes the issue seems hidden yet still produces errors
sometimes ~~it flickers~ there is jumping when no more scroll events occur

**Expected behavior**

No continuous jumping of elements when scrolling stops. ~~flapping up and down of homeScreenFeedTabs~~

**Screenshots**

~~Can't make a video at moment.~~
I attached two videos, one github cant parse the codecs inside the container.
The 2nd embeds fine.

Filter on "aspect-ratio" and CSS in the inspector to watch happen when triggered.

**Details**

 - Platform: firefox
 - Platform version:  118.0.1 in linux
 - App version: main

**Additional context**

~~When I delete the 2nd 'translateY' from the CSS inspector panel, issue is resolved reduced.~~ I thought it was eliminated but the issue recurs.

https://github.com/search?q=repo%3Abluesky-social%2Fsocial-app+translateY%288px%29&type=code

https://github.com/bluesky-social/social-app/blame/fd5bbb27699942f7d741d074eafdf16bfc9ecdd6/web/index.html#L151

https://github.com/bluesky-social/social-app/assets/125841094/18dcc9d0-19bd-41bb-9131-ea43f0df1343

https://github.com/bluesky-social/social-app/assets/125841094/ba6ad519-ef3e-44f9-b1ae-43f9c4692a08

**Comment by pfrazee** [comment]
I'm not able to reproduce this, and I wonder if this is either a graphics driver issue. That said, we could try a different way to do this css. Could you try this?

```css
      [data-tooltip]::after {
        content: attr(data-tooltip);
        display: none;
        position: absolute;
        bottom: -8px; /* CHANGED FROM 0 */
        left: 50%;
        transform: translateY(100%) translateX(-50%); /* DROPPED THE SECOND TRANSLATE */
        padding: 4px 10px;
        border-radius: 10px;
        background: var(--backgroundLight);
        color: var(--text);
        text-align: center;
        white-space: nowrap;
        font-size: 12px;
        z-index: 10;
      }
```
