### ISSUE TITLE
Docker compose with clear instructions on selfhosting needed to connect with app

### ISSUE THREAD

**Issue by HakaishinShwet** [bluesky-social/social-app#5230]
Project is great but docker compose with proper instructions on selfhosting and to be able connect with app is much more needed in my opinion

**Comment by AverageHelper** [comment]
If it helps any, I managed to get a version running this way:

1. Clone `social-app` to a subdirectory, e.g. `git clone https://github.com/bluesky-social/social-app.git repo`
2. Create a `compose.yml` file in the current directory with something like the following:
```yml
services:
  bsky-social-app:
    build:
      context: ./repo
    # You can set the `appview-host` to an appropriate PDS for your setup, but bsky's one works:
    command: ["/usr/bin/bskyweb", "serve", "--appview-host=https://public.api.bsky.app"]
    ports:
      - 8100:8100
    restart: unless-stopped
    # Basic security stuffs; this webserver doesn't need any extra privileges, so these help keep the container contained:
    read_only: true
    user: 1000:1000
    cap_drop:
      - ALL
    security_opt:
      - "no-new-privileges:true"
    deploy:
      resources:
        # These should vary depending on what resources you have and want to allocate to serving the appview:
        limits:
          cpus: '0.5'
          memory: 200MB
```
3. Inside the `repo` directory, check out a specific tag, e.g. `git checkout 1.107.0` (Be sure to update this periodically. Consider adding https://github.com/bluesky-social/social-app/releases.atom to an RSS reader to notify of new releases.)
4. Start the container using e.g. `docker compose up -d`
5. Point a reverse-proxy such as [Caddy](https://caddyserver.com) at port `8100`
6. ???
7. profit

When you update the appview code or make changes to your copy, checkout the new tag in `repo` and then re-build the container with e.g. `docker compose up -d --no-deps --build`

You should be able to log into your new appview instance via a web browser now. The version string in your `/settings/about` page will have `dev (prod)` at the end. Not sure why this doesn't use a hash like the official one tho.

As for being able to "connect with app", afaik the app and the web frontends are each separate appviews, so you'll have to build the app yourself locally and run that on your own device. The first-party mobile app can select a PDS, but not an appview URL afaik.
